# Generated by Django 5.1.5 on 2025-01-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_calendar_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
